version: '3.4'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    networks:
      rede1:
        ipv4_address: 172.16.238.3
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U root -d database'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s
  cache:
    container_name: redis
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      rede1:
        ipv4_address: 172.16.238.6
    volumes:
      - cache:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 30s
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      rede1:
        ipv4_address: 172.16.238.4
    depends_on:
      - db
  api:
    container_name: api_gateway
    image: d3adsec/api_gateway
    ports:
      - "8000:8000"
    networks:
      rede1:
        ipv4_address: 172.16.238.5
    depends_on:
      db:
        condition: service_started
      cache:
        condition: service_healthy
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      rede1:
        ipv4_address: 172.16.238.10
    volumes:
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
  ms_admin:
    container_name: ms_admin
    image: d3adsec/ms_admin
    networks:
      - rede1
  ms_authors:
    container_name: ms_authors
    image: d3adsec/ms_authors
    networks:
      - rede1
  ms_authors_all:
    container_name: ms_authors_all
    image: d3adsec/ms_authors_all
    networks:
      - rede1
  ms_comments:
    container_name: ms_comments
    image: d3adsec/ms_comments
    networks:
      - rede1
  ms_comments_delete:
    container_name: ms_comments_delete
    image: d3adsec/ms_comments_delete
    networks:
      - rede1
  ms_comments_update:
    container_name: ms_comments_update
    image: d3adsec/ms_comments_update
    networks:
      - rede1
  ms_news:
    container_name: ms_news
    image: d3adsec/ms_news
    networks:
      - rede1
  ms_news_admin:
    container_name: ms_news_admin
    image: d3adsec/ms_news_admin
    networks:
      - rede1
  ms_news_all:
    container_name: ms_news_all
    image: d3adsec/ms_news_all]
    networks:
      - rede1
  ms_news_author:
    container_name: ms_news_author
    image: d3adsec/ms_news_author
    networks:
      - rede1
  ms_news_delete:
    container_name: ms_news_delete
    image: d3adsec/ms_news_delete
    networks:
      - rede1
  ms_news_details:
    container_name: ms_news_details
    image: d3adsec/ms_news_details
    networks:
      - rede1
  ms_news_nickname:
    container_name: ms_news_nickname
    image: d3adsec/ms_news_nickname
    networks:
      - rede1
  ms_news_publish:
    container_name: ms_news_publish
    image: d3adsec/ms_news_publish
    networks:
      - rede1
  ms_news_update:
    container_name: ms_news_update
    image: d3adsec/ms_news_update
    networks:
      - rede1
  ms_reactions:
    container_name: ms_reactions
    image: d3adsec/ms_reactions
    networks:
      - rede1
  ms_reactions_update:
    container_name: ms_reactions_update
    image: d3adsec/ms_reactions_update
    networks:
      - rede1
  ms_readers:
    container_name: ms_readers
    image: d3adsec/ms_readers
    networks:
      - rede1
  ms_user_activate:
    container_name: ms_user_activate
    image: d3adsec/ms_user_activate
    networks:
      - rede1
  ms_user_block:
    container_name: ms_user_block
    image: d3adsec/ms_user_block
    networks:
      - rede1
  ms_user_update:
    container_name: ms_user_update
    image: d3adsec/ms_user_update
    networks:
      - rede1

networks:
  rede1:
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.238.0/16

volumes:
  db:
    driver: local
  cache:
    driver: local
